spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/struts?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root

